  ('151 Proof Rum'),
  ('7-Up'),
  ('7-up'),
  ('Absinthe'),
  ('Absolut Citron'),
  ('Absolut Kurant'),
  ('Absolut Peppar'),
  ('Absolut Vodka'),
  ('Advocaat'),
  ('Agave Syrup'),
  ('Ale'),
  ('Allspice'),
  ('Almond'),
  ('Almond Flavoring'),
  ('Amaretto'),
  ('Amaro Montenegro'),
  ('Angelica Root'),
  ('Angostura Bitters'),
  ('Anis'),
  ('Anise'),
  ('Anisette'),
  ('Aperol'),
  ('Apfelkorn'),
  ('Apple'),
  ('Apple Brandy'),
  ('Apple Cider'),
  ('Apple Juice'),
  ('Apple Schnapps'),
  ('Applejack'),
  ('Apricot'),
  ('Apricot Brandy'),
  ('Apricot Nectar'),
  ('Aquavit'),
  ('Asafoetida'),
  ('Añejo Rum'),
  ('Bacardi Limon'),
  ('Baileys Irish Cream'),
  ('Banana'),
  ('Banana Liqueur'),
  ('Basil'),
  ('Beer'),
  ('Benedictine'),
  ('Berries'),
  ('Bitter Lemon'),
  ('Bitters'),
  ('Black Pepper'),
  ('Black Sambuca'),
  ('Blackberries'),
  ('Blackberry Brandy'),
  ('Blackcurrant Cordial'),
  ('Blackcurrant Squash'),
  ('Blackstrap Rum'),
  ('Blended Scotch'),
  ('Blended Whiskey'),
  ('Blood Orange'),
  ('Blue Curacao'),
  ('Blueberries'),
  ('Bourbon'),
  ('Brandy'),
  ('Brown Sugar'),
  ('Butter'),
  ('Butterscotch Schnapps'),
  ('Cachaca'),
  ('Campari'),
  ('Candy'),
  ('Cantaloupe'),
  ('Caramel Coloring'),
  ('Caramel Sauce'),
  ('Carbonated Soft Drink'),
  ('Carbonated Water'),
  ('Cardamom'),
  ('Carrot'),
  ('Cayenne Pepper'),
  ('Celery Salt'),
  ('Chambord Raspberry Liqueur'),
  ('Champagne'),
  ('Cherries'),
  ('Cherry'),
  ('Cherry Brandy'),
  ('Cherry Grenadine'),
  ('Cherry Heering'),
  ('Cherry Juice'),
  ('Cherry Liqueur'),
  ('Chocolate'),
  ('Chocolate Ice-cream'),
  ('Chocolate Liqueur'),
  ('Chocolate Milk'),
  ('Chocolate Sauce'),
  ('Chocolate Syrup'),
  ('Cider'),
  ('Cinnamon'),
  ('Cloves'),
  ('Club Soda'),
  ('Coca-Cola'),
  ('Cocoa Powder'),
  ('Coconut Liqueur'),
  ('Coconut Milk'),
  ('Coconut Rum'),
  ('Coconut Syrup'),
  ('Coffee'),
  ('Coffee Brandy'),
  ('Coffee Liqueur'),
  ('Cognac'),
  ('Cointreau'),
  ('Condensed Milk'),
  ('Coriander'),
  ('Corn Syrup'),
  ('Cornstarch'),
  ('Corona'),
  ('Cranberries'),
  ('Cranberry Juice'),
  ('Cranberry Vodka'),
  ('Cream'),
  ('Cream Of Coconut'),
  ('Creme De Banane'),
  ('Creme De Cacao'),
  ('Creme De Cassis'),
  ('Creme De Mure'),
  ('Crown Royal'),
  ('Cucumber'),
  ('Cumin Seed'),
  ('Curacao'),
  ('Daiquiri Mix'),
  ('Dark Creme De Cacao'),
  ('Dark Rum'),
  ('Demerara Sugar'),
  ('Dr. Pepper'),
  ('Drambuie'),
  ('Dry Vermouth'),
  ('Dubonnet Rouge'),
  ('Egg'),
  ('Egg White'),
  ('Egg Yolk'),
  ('Elderflower Cordial'),
  ('Erin Cream'),
  ('Espresso'),
  ('Everclear'),
  ('Falernum'),
  ('Fennel Seeds'),
  ('Figs'),
  ('Firewater'),
  ('Food Coloring'),
  ('Frangelico'),
  ('Fresca'),
  ('Fresh Lemon Juice'),
  ('Fresh Lime Juice'),
  ('Fruit'),
  ('Fruit Juice'),
  ('Fruit Punch'),
  ('Galliano'),
  ('Gin'),
  ('Ginger'),
  ('Ginger Ale'),
  ('Ginger Beer'),
  ('Ginger Syrup'),
  ('Glycerine'),
  ('Godiva Liqueur'),
  ('Gold Rum'),
  ('Gold Tequila'),
  ('Goldschlager'),
  ('Grain Alcohol'),
  ('Grand Marnier'),
  ('Grape Juice'),
  ('Grape Soda'),
  ('Grapefruit Juice'),
  ('Grapes'),
  ('Green Chartreuse'),
  ('Green Creme De Menthe'),
  ('Grenadine'),
  ('Guava Juice'),
  ('Guinness Stout'),
  ('Half-and-half'),
  ('Heavy Cream'),
  ('Honey'),
  ('Honey Syrup'),
  ('Hot Chocolate'),
  ('Hot Damn'),
  ('Hot Sauce'),
  ('Hpnotiq'),
  ('Ice'),
  ('Iced Tea'),
  ('Irish Cream'),
  ('Irish Whiskey'),
  ('Islay Single Malt Scotch'),
  ('Jack Daniels'),
  ('Jagermeister'),
  ('Jello'),
  ('Jim Beam'),
  ('Johnnie Walker'),
  ('Jägermeister'),
  ('Kahlua'),
  ('Kirschwasser'),
  ('Kiwi'),
  ('Kiwi Liqueur'),
  ('Kool-Aid'),
  ('Kummel'),
  ('Lager'),
  ('Lavender'),
  ('Lemon'),
  ('Lemon Juice'),
  ('Lemon Peel'),
  ('Lemon Vodka'),
  ('Lemon-lime Soda'),
  ('Lemonade'),
  ('Licorice Root'),
  ('Light Cream'),
  ('Light Rum'),
  ('Lillet'),
  ('Lillet Blanc'),
  ('Lime'),
  ('Lime Juice'),
  ('Lime Juice Cordial'),
  ('Lime Peel'),
  ('Lime Vodka'),
  ('Limeade'),
  ('Malibu Rum'),
  ('Mango'),
  ('Maple Syrup'),
  ('Maraschino Cherry'),
  ('Maraschino Liqueur'),
  ('Marjoram Leaves'),
  ('Marshmallows'),
  ('Maui'),
  ('Melon Liqueur'),
  ('Mezcal'),
  ('Midori Melon Liqueur'),
  ('Milk'),
  ('Mini-snickers Bars'),
  ('Mint'),
  ('Mint Syrup'),
  ('Mountain Dew'),
  ('Nutmeg'),
  ('Olive'),
  ('Olive Brine'),
  ('Orange'),
  ('Orange Bitters'),
  ('Orange Curacao'),
  ('Orange Juice'),
  ('Orange Peel'),
  ('Orange Spiral'),
  ('Oreo Cookie'),
  ('Orgeat Syrup'),
  ('Ouzo'),
  ('Papaya'),
  ('Passion Fruit Juice'),
  ('Passion Fruit Syrup'),
  ('Passoa'),
  ('Peach Bitters'),
  ('Peach Brandy'),
  ('Peach Nectar'),
  ('Peach Schnapps'),
  ('Peach Vodka'),
  ('Peachtree Schnapps'),
  ('Pepper'),
  ('Peppermint Extract'),
  ('Peppermint Schnapps'),
  ('Pepsi Cola'),
  ('Pernod'),
  ('Peychaud Bitters'),
  ('Pina Colada Mix'),
  ('Pineapple'),
  ('Pineapple Juice'),
  ('Pineapple Syrup'),
  ('Pink Lemonade'),
  ('Pisang Ambon'),
  ('Pisco'),
  ('Pomegranate Juice'),
  ('Port'),
  ('Powdered Sugar'),
  ('Prosecco'),
  ('Raisins'),
  ('Raspberry Liqueur'),
  ('Raspberry Syrup'),
  ('Raspberry Vodka'),
  ('Red Chili Flakes'),
  ('Red Wine'),
  ('Ricard'),
  ('Root Beer'),
  ('Rose'),
  ('Rosemary'),
  ('Rosemary Syrup'),
  ('Rosso Vermouth'),
  ('Ruby Port'),
  ('Rum'),
  ('Rye Whiskey'),
  ('Salt'),
  ('Salted Chocolate'),
  ('Sambuca'),
  ('Sarsaparilla'),
  ('Schweppes Russchian'),
  ('Scotch'),
  ('Sherbet'),
  ('Sherry'),
  ('Sirup Of Roses'),
  ('Sloe Gin'),
  ('Soda Water'),
  ('Sour Mix'),
  ('Southern Comfort'),
  ('Soy Sauce'),
  ('Spiced Rum'),
  ('Sprite'),
  ('St. Germain'),
  ('Strawberries'),
  ('Strawberry Liqueur'),
  ('Strawberry Schnapps'),
  ('Sugar'),
  ('Sugar Syrup'),
  ('Surge'),
  ('Sweet And Sour'),
  ('Sweet Vermouth'),
  ('Tabasco Sauce'),
  ('Tea'),
  ('Tennessee Whiskey'),
  ('Tequila'),
  ('Thyme'),
  ('Tia Maria'),
  ('Tomato Juice'),
  ('Tonic Water'),
  ('Triple Sec'),
  ('Tropicana'),
  ('Vanilla'),
  ('Vanilla Extract'),
  ('Vanilla Ice-Cream'),
  ('Vanilla Ice-cream'),
  ('Vanilla Syrup'),
  ('Vermouth'),
  ('Vodka'),
  ('Water'),
  ('Watermelon'),
  ('Whipped Cream'),
  ('Whipping Cream'),
  ('Whiskey'),
  ('Whisky'),
  ('White Creme De Menthe'),
  ('White Rum'),
  ('White Wine'),
  ('Wild Turkey'),
  ('Wine'),
  ('Worcestershire Sauce'),
  ('Wormwood'),
  ('Yellow Chartreuse'),
  ('Yoghurt'),
  ('Yukon Jack'),
  ('Zima'),
