  ('7-up'),
  ('Agave Syrup'),
  ('Allspice'),
  ('Almond Flavoring'),
  ('Almond'),
  ('Angelica Root'),
  ('Angostura Bitters'),
  ('Anis'),
  ('Anise'),
  ('Anisette'),
  ('Apple Cider'),
  ('Apple Juice'),
  ('Apple'),
  ('Apricot Nectar'),
  ('Apricot'),
  ('Aquavit'),
  ('Banana'),
  ('Basil'),
  ('Berries'),
  ('Bitter Lemon'),
  ('Bitters'),
  ('Black Pepper'),
  ('Blackberries'),
  ('Blackcurrant Squash'),
  ('Blood Orange'),
  ('Blueberries'),
  ('Brown Sugar'),
  ('Butter'),
  ('Candy'),
  ('Cantaloupe'),
  ('Caramel Coloring'),
  ('Caramel Sauce'),
  ('Carbonated Soft Drink'),
  ('Carbonated Water'),
  ('Cardamom'),
  ('Carrot'),
  ('Cayenne Pepper'),
  ('Celery Salt'),
  ('Cherries'),
  ('Cherry Juice'),
  ('Cherry'),
  ('Chocolate Ice-cream'),
  ('Chocolate Milk'),
  ('Chocolate Sauce'),
  ('Chocolate Syrup'),
  ('Chocolate'),
  ('Cinnamon'),
  ('Cloves'),
  ('Club Soda'),
  ('Coca-cola'),
  ('Cocoa Powder'),
  ('Coconut Milk'),
  ('Coconut Syrup'),
  ('Coffee'),
  ('Condensed Milk'),
  ('Coriander'),
  ('Corn Syrup'),
  ('Cornstarch'),
  ('Cranberries'),
  ('Cranberry Juice'),
  ('Cream Of Coconut'),
  ('Cream'),
  ('Cucumber'),
  ('Cumin Seed'),
  ('Daiquiri Mix'),
  ('Demerara Sugar'),
  ('Dr. Pepper'),
  ('Egg White'),
  ('Egg Yolk'),
  ('Egg'),
  ('Erin Cream'),
  ('Espresso'),
  ('Fennel Seeds'),
  ('Figs'),
  ('Food Coloring'),
  ('Fresca'),
  ('Fresh Lemon Juice'),
  ('Fresh Lime Juice'),
  ('Fruit Juice'),
  ('Fruit Punch'),
  ('Fruit'),
  ('Ginger Ale'),
  ('Ginger Beer'),
  ('Ginger Syrup'),
  ('Ginger'),
  ('Glycerine'),
  ('Grape Juice'),
  ('Grape Soda'),
  ('Grapefruit Juice'),
  ('Grapes'),
  ('Guava Juice'),
  ('Half-and-half'),
  ('Heavy Cream'),
  ('Honey Syrup'),
  ('Honey'),
  ('Hot Chocolate'),
  ('Hot Sauce'),
  ('Ice'),
  ('Iced Tea'),
  ('Irish Cream'),
  ('Jello'),
  ('Kiwi'),
  ('Kool-aid'),
  ('Lavender'),
  ('Lemon Juice'),
  ('Lemon Peel'),
  ('Lemon'),
  ('Lemon-lime Soda'),
  ('Lemonade'),
  ('Licorice Root'),
  ('Light Cream'),
  ('Lime Juice'),
  ('Lime Peel'),
  ('Lime'),
  ('Limeade'),
  ('Mango'),
  ('Maple Syrup'),
  ('Maraschino Cherry'),
  ('Marjoram Leaves'),
  ('Marshmallows'),
  ('Milk'),
  ('Mini-snickers Bars'),
  ('Mint Syrup'),
  ('Mint'),
  ('Mountain Dew'),
  ('Nutmeg'),
  ('Olive Brine'),
  ('Olive'),
  ('Orange Bitters'),
  ('Orange Juice'),
  ('Orange Peel'),
  ('Orange Spiral'),
  ('Orange'),
  ('Oreo Cookie'),
  ('Orgeat Syrup'),
  ('Papaya'),
  ('Passion Fruit Juice'),
  ('Passion Fruit Syrup'),
  ('Peach Bitters'),
  ('Peach Nectar'),
  ('Pepper'),
  ('Peppermint Extract'),
  ('Pepsi Cola'),
  ('Peychaud Bitters'),
  ('Pina Colada Mix'),
  ('Pineapple Juice'),
  ('Pineapple Syrup'),
  ('Pineapple'),
  ('Pink Lemonade'),
  ('Pomegranate Juice'),
  ('Powdered Sugar'),
  ('Raisins'),
  ('Raspberry Syrup'),
  ('Red Chili Flakes'),
  ('Root Beer'),
  ('Rosemary Syrup'),
  ('Rosemary'),
  ('Salt'),
  ('Salted Chocolate'),
  ('Sarsaparilla'),
  ('Sherbet'),
  ('Sirup Of Roses'),
  ('Soda Water'),
  ('Sour Mix'),
  ('Soy Sauce'),
  ('Sprite'),
  ('St. Germain'),
  ('Strawberries'),
  ('Strawberry Liqueur'),
  ('Strawberry Schnapps'),
  ('Sugar Syrup'),
  ('Sugar'),
  ('Sweet And Sour'),
  ('Tabasco Sauce'),
  ('Tea'),
  ('Thyme'),
  ('Tomato Juice'),
  ('Tonic Water'),
  ('Tropicana'),
  ('Vanilla Extract'),
  ('Vanilla Ice-cream'),
  ('Vanilla Syrup'),
  ('Vanilla'),
  ('Water'),
  ('Watermelon'),
  ('Whipped Cream'),
  ('Whipping Cream'),
  ('Worcestershire Sauce'),
  ('Wormwood'),
  ('Yoghurt'),
  ('Zima'),
